DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE AUTHORS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(70));
CREATE TABLE GENRES(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, TITLE VARCHAR(20));
CREATE TABLE BOOKS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, TITLE VARCHAR(100), AUTHOR_ID BIGINT REFERENCES AUTHORS(ID), GENRE_ID BIGINT REFERENCES GENRES(ID));
CREATE TABLE COMMENTS(ID BIGINT NOT NULL AUTO_INCREMENT, BOOK_ID BIGINT REFERENCES BOOKS(ID) ON DELETE CASCADE, COMMENT VARCHAR(255), PRIMARY KEY (ID));


